name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26.1.2

    steps:
    - uses: actions/checkout@v3
    - name: Get deps
      run: rebar3 get-deps
    - name: Compile
      run: rebar3 compile
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Run tests
      run: rebar3 do eunit, ct
